# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rip <- function(D_R, N, modulus, dim_max, threshold, do_cocycles) {
    .Call('_tdatools_rip', PACKAGE = 'tdatools', D_R, N, modulus, dim_max, threshold, do_cocycles)
}

