CC = gcc
CFLAGS  = -g -Wall -O3

all: Anova BinningOnDiagram ClassifierBasedOnAllDimensions ClassifierBasedOnSingleDimension ComputeAverage DistanceMatrix HistogramsOfBarcodesLength MinMaxBarcodes NormalizeBarcodes NthMoment PermutationTest PlotOfLandscape PlotsOfDiagram PlotsOfDiagrams PlotsOfLandscapesViaScripts PlotsOfLandscapeViaScripts ScalarProducts StandardDeviation T-StudentTest VerifyAverageOfPopulationWithT-Test

Anova:
	$(CXX) $(CXXFLAGS) -o Anova Anova.cpp

BinningOnDiagram:
	$(CXX) $(CXXFLAGS) -o BinningOnDiagram BinningOnDiagram.cpp

ClassifierBasedOnAllDimensions:
	$(CXX) $(CXXFLAGS) -o ClassifierBasedOnAllDimensions ClassifierBasedOnAllDimensions.cpp

ClassifierBasedOnSingleDimension:
	$(CXX) $(CXXFLAGS) -o ClassifierBasedOnSingleDimension ClassifierBasedOnSingleDimension.cpp

ComputeAverage:
	$(CXX) $(CXXFLAGS) -o ComputeAverage ComputeAverage.cpp

DistanceMatrix:
	$(CXX) $(CXXFLAGS) -o DistanceMatrix DistanceMatrix.cpp

HistogramsOfBarcodesLength:
	$(CXX) $(CXXFLAGS) -o HistogramsOfBarcodesLength HistogramsOfBarcodesLength.cpp

MinMaxBarcodes:
	$(CXX) $(CXXFLAGS) -o MinMaxBarcodes MinMaxBarcodes.cpp

NormalizeBarcodes:
	$(CXX) $(CXXFLAGS) -o NormalizeBarcodes NormalizeBarcodes.cpp

NthMoment:
	$(CXX) $(CXXFLAGS) -o NthMoment NthMoment.cpp

PermutationTest:
	$(CXX) $(CXXFLAGS) -o PermutationTest PermutationTest.cpp

PlotOfLandscape:
	$(CXX) $(CXXFLAGS) -o PlotOfLandscape PlotOfLandscape.cpp

PlotsOfDiagram:
	$(CXX) $(CXXFLAGS) -o PlotsOfDiagram PlotsOfDiagram.cpp

PlotsOfDiagrams:
	$(CXX) $(CXXFLAGS) -o PlotsOfDiagrams PlotsOfDiagrams.cpp

PlotsOfLandscapesViaScripts:
	$(CXX) $(CXXFLAGS) -o PlotsOfLandscapesViaScripts PlotsOfLandscapesViaScripts.cpp

PlotsOfLandscapeViaScripts:
	$(CXX) $(CXXFLAGS) -o PlotsOfLandscapeViaScripts PlotsOfLandscapeViaScripts.cpp

ScalarProducts:
	$(CXX) $(CXXFLAGS) -o ScalarProducts ScalarProducts.cpp

StandardDeviation:
	$(CXX) $(CXXFLAGS) -o StandardDeviation StandardDeviation.cpp

T-StudentTest:
	$(CXX) $(CXXFLAGS) -o T-StudentTest T-StudentTest.cpp

VerifyAverageOfPopulationWithT-Test:
	$(CXX) $(CXXFLAGS) -o VerifyAverageOfPopulationWithT-Test VerifyAverageOfPopulationWithT-Test.cpp

.PHONY: clean

clean:
	rm -f Anova
	rm -f BinningOnDiagram
	rm -f ClassifierBasedOnAllDimensions
	rm -f ClassifierBasedOnSingleDimension
	rm -f ComputeAverage
	rm -f DistanceMatrix
	rm -f HistogramsOfBarcodesLength.cpp
	rm -f minMaxBarcodes
	rm -f NormalizeBarcodes
	rm -f NthMoment
	rm -f PermutationTest
	rm -f PlotOfLandscape
	rm -f PlotsOfDiagram
	rm -f PlotsOfDiagrams
	rm -f PlotsOfLandscapesViaScripts
	rm -f PlotsOfLandscapeViaScripts
	rm -f ScalarProducts
	rm -f StandardDeviation
	rm -f T-StudentTest
	rm -f VerifyAverageOfPopulationWithT-Test
