// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_Landscape();
RcppExport SEXP _rcpp_module_boot_Diagram();
RcppExport SEXP _rcpp_module_boot_H0();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_Landscape", (DL_FUNC) &_rcpp_module_boot_Landscape, 0},
    {"_rcpp_module_boot_Diagram", (DL_FUNC) &_rcpp_module_boot_Diagram, 0},
    {"_rcpp_module_boot_H0", (DL_FUNC) &_rcpp_module_boot_H0, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_tdatools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
